//
// Copyright © 2025 osy. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

#ifndef QEMUKeyCode_h
#define QEMUKeyCode_h

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, QEMUKeyCode) {
    QEMUKeyCodeKeyUnmapped,
    QEMUKeyCodeKeyShift,
    QEMUKeyCodeKeyShiftR,
    QEMUKeyCodeKeyAlt,
    QEMUKeyCodeKeyAltR,
    QEMUKeyCodeKeyCtrl,
    QEMUKeyCodeKeyCtrlR,
    QEMUKeyCodeKeyMenu,
    QEMUKeyCodeKeyEsc,
    QEMUKeyCodeKey1,
    QEMUKeyCodeKey2,
    QEMUKeyCodeKey3,
    QEMUKeyCodeKey4,
    QEMUKeyCodeKey5,
    QEMUKeyCodeKey6,
    QEMUKeyCodeKey7,
    QEMUKeyCodeKey8,
    QEMUKeyCodeKey9,
    QEMUKeyCodeKey0,
    QEMUKeyCodeKeyMinus,
    QEMUKeyCodeKeyEqual,
    QEMUKeyCodeKeyBackspace,
    QEMUKeyCodeKeyTab,
    QEMUKeyCodeKeyQ,
    QEMUKeyCodeKeyW,
    QEMUKeyCodeKeyE,
    QEMUKeyCodeKeyR,
    QEMUKeyCodeKeyT,
    QEMUKeyCodeKeyY,
    QEMUKeyCodeKeyU,
    QEMUKeyCodeKeyI,
    QEMUKeyCodeKeyO,
    QEMUKeyCodeKeyP,
    QEMUKeyCodeKeyBracketLeft,
    QEMUKeyCodeKeyBracketRight,
    QEMUKeyCodeKeyRet,
    QEMUKeyCodeKeyA,
    QEMUKeyCodeKeyS,
    QEMUKeyCodeKeyD,
    QEMUKeyCodeKeyF,
    QEMUKeyCodeKeyG,
    QEMUKeyCodeKeyH,
    QEMUKeyCodeKeyJ,
    QEMUKeyCodeKeyK,
    QEMUKeyCodeKeyL,
    QEMUKeyCodeKeySemicolon,
    QEMUKeyCodeKeyApostrophe,
    QEMUKeyCodeKeyGraveAccent,
    QEMUKeyCodeKeyBackslash,
    QEMUKeyCodeKeyZ,
    QEMUKeyCodeKeyX,
    QEMUKeyCodeKeyC,
    QEMUKeyCodeKeyV,
    QEMUKeyCodeKeyB,
    QEMUKeyCodeKeyN,
    QEMUKeyCodeKeyM,
    QEMUKeyCodeKeyComma,
    QEMUKeyCodeKeyDot,
    QEMUKeyCodeKeySlash,
    QEMUKeyCodeKeyAsterisk,
    QEMUKeyCodeKeySpc,
    QEMUKeyCodeKeyCapsLock,
    QEMUKeyCodeKeyF1,
    QEMUKeyCodeKeyF2,
    QEMUKeyCodeKeyF3,
    QEMUKeyCodeKeyF4,
    QEMUKeyCodeKeyF5,
    QEMUKeyCodeKeyF6,
    QEMUKeyCodeKeyF7,
    QEMUKeyCodeKeyF8,
    QEMUKeyCodeKeyF9,
    QEMUKeyCodeKeyF10,
    QEMUKeyCodeKeyNumLock,
    QEMUKeyCodeKeyScrollLock,
    QEMUKeyCodeKeyKpDivide,
    QEMUKeyCodeKeyKpMultiply,
    QEMUKeyCodeKeyKpSubtract,
    QEMUKeyCodeKeyKpAdd,
    QEMUKeyCodeKeyKpEnter,
    QEMUKeyCodeKeyKpDecimal,
    QEMUKeyCodeKeySysRq,
    QEMUKeyCodeKeyKp0,
    QEMUKeyCodeKeyKp1,
    QEMUKeyCodeKeyKp2,
    QEMUKeyCodeKeyKp3,
    QEMUKeyCodeKeyKp4,
    QEMUKeyCodeKeyKp5,
    QEMUKeyCodeKeyKp6,
    QEMUKeyCodeKeyKp7,
    QEMUKeyCodeKeyKp8,
    QEMUKeyCodeKeyKp9,
    QEMUKeyCodeKeyLess,
    QEMUKeyCodeKeyF11,
    QEMUKeyCodeKeyF12,
    QEMUKeyCodeKeyPrint,
    QEMUKeyCodeKeyHome,
    QEMUKeyCodeKeyPgUp,
    QEMUKeyCodeKeyPgDn,
    QEMUKeyCodeKeyEnd,
    QEMUKeyCodeKeyLeft,
    QEMUKeyCodeKeyUp,
    QEMUKeyCodeKeyDown,
    QEMUKeyCodeKeyRight,
    QEMUKeyCodeKeyInsert,
    QEMUKeyCodeKeyDelete,
    QEMUKeyCodeKeyStop,
    QEMUKeyCodeKeyAgain,
    QEMUKeyCodeKeyProps,
    QEMUKeyCodeKeyUndo,
    QEMUKeyCodeKeyFront,
    QEMUKeyCodeKeyCopy,
    QEMUKeyCodeKeyOpen,
    QEMUKeyCodeKeyPaste,
    QEMUKeyCodeKeyFind,
    QEMUKeyCodeKeyCut,
    QEMUKeyCodeKeyLf,
    QEMUKeyCodeKeyHelp,
    QEMUKeyCodeKeyMetaL,
    QEMUKeyCodeKeyMetaR,
    QEMUKeyCodeKeyCompose,
    QEMUKeyCodeKeyPause,
    QEMUKeyCodeKeyRo,
    QEMUKeyCodeKeyHiragana,
    QEMUKeyCodeKeyHenkan,
    QEMUKeyCodeKeyYen,
    QEMUKeyCodeKeyMuhenkan,
    QEMUKeyCodeKeyKatakanaHiragana,
    QEMUKeyCodeKeyKpComma,
    QEMUKeyCodeKeyKpEquals,
    QEMUKeyCodeKeyPower,
    QEMUKeyCodeKeySleep,
    QEMUKeyCodeKeyWake,
    QEMUKeyCodeKeyAudioNext,
    QEMUKeyCodeKeyAudioPrev,
    QEMUKeyCodeKeyAudioStop,
    QEMUKeyCodeKeyAudioPlay,
    QEMUKeyCodeKeyAudioMute,
    QEMUKeyCodeKeyVolumeUp,
    QEMUKeyCodeKeyVolumeDown,
    QEMUKeyCodeKeyMediaSelect,
    QEMUKeyCodeKeyMail,
    QEMUKeyCodeKeyCalculator,
    QEMUKeyCodeKeyComputer,
    QEMUKeyCodeKeyAcHome,
    QEMUKeyCodeKeyAcBack,
    QEMUKeyCodeKeyAcForward,
    QEMUKeyCodeKeyAcRefresh,
    QEMUKeyCodeKeyAcBookmarks,
    QEMUKeyCodeKeyLang1,
    QEMUKeyCodeKeyLang2,
    QEMUKeyCodeKeyF13,
    QEMUKeyCodeKeyF14,
    QEMUKeyCodeKeyF15,
    QEMUKeyCodeKeyF16,
    QEMUKeyCodeKeyF17,
    QEMUKeyCodeKeyF18,
    QEMUKeyCodeKeyF19,
    QEMUKeyCodeKeyF20,
    QEMUKeyCodeKeyF21,
    QEMUKeyCodeKeyF22,
    QEMUKeyCodeKeyF23,
    QEMUKeyCodeKeyF24,
    QEMUKeyCodeKeyMax
};

#endif /* QEMUKeyCode_h */
